### ISSUE TITLE
NPC not chasing and doesn't deal damage

### ISSUE THREAD

**Issue by AndyLee-SH** [CaydenJessen/Stay-Hidden_GAME#10]
Describe the bug
NPC doesn't chase unless Player is in the light.
When NPC touches Player, no damage is being dealt to player.

To Reproduce
Steps to reproduce the behaviour:

Player goes into line of sight of NPC, NPC doesn't chase.
Player touches NPC, Player's health stays the same at 100%.
NPC only chase if Player is in Light area. 

Desktop (please complete the following information):

OS: Windows 10
Unity Version 2022.1.7

**Comment by CaydenJessen** [comment]
To fix the line of sight detection and chase I had to re-reference the scripts for the new enemy sprites.

The enemy damage script wasn't working so I moved it to the player health. This will have to be moved and optimised back into a separate script when we want teach enemy to do a certain amount of damage.
