### ISSUE TITLE
NPC Sprite changes during game.

### ISSUE THREAD

**Issue by AndyLee-SH** [CaydenJessen/Stay-Hidden_GAME#11]
Describe the bug
Grandma's NPC changes during a play through. Changes to Butler's NPC sprite.

To Reproduce
Steps to reproduce the behaviour:

Player plays through the game.
Grandma NPC changes to Butler NPC. 

Desktop (please complete the following information):

OS: Windows 10
Unity Version 2022.1.7

**Comment by ILikeDogss** [comment]
Issue solved
