### ISSUE TITLE
Green Room Level Player can not hide

### ISSUE THREAD

**Issue by AndyLee-SH** [CaydenJessen/Stay-Hidden_GAME#18]
Describe the bug
Player Can not hide in level 2 the Green Room.

To Reproduce
Steps to reproduce the behaviour:

Player loads into level two, they can walk and jump
when player tries to Hide, this function seems disabled or it is not working at all.

Desktop (please complete the following information):
OS: Windows 10
Unity Version 2022.1.7

**Comment by CaydenJessen** [comment]
Fixed:  Referencing scripts and objects in the inspector menu
