### ISSUE TITLE
Door Animation not working

### ISSUE THREAD

**Issue by AndyLee-SH** [CaydenJessen/Stay-Hidden_GAME#21]
Describe the bug
Stage 2 and stage 3 doors on these levels are stuck in the in-between opening sprite.

To Reproduce
Game load
go to where the doors are located
the door is showing the half open/ closed sprite
Door function works 
just the animation is not working.

Desktop (please complete the following information):
OS: Windows 10
Unity Version 2022.1.7

**Comment by ILikeDogss** [comment]
Fixed by reconstructing the animations, made new prefabs for each level door
