### ISSUE TITLE
Player Jump issue

### ISSUE THREAD

**Issue by AndyLee-SH** [CaydenJessen/Stay-Hidden_GAME#4]
**Describe the bug**
When a player gets pushed by enemy, sometimes player can not jump afterwards.

**To Reproduce**
1. Player run up to NPC
2. NPC Chase
3. NPC contact Player
4. Player disengaged
5. Player can not jump.

**Expected behavior**
Player can jump whenever Jump button is activated

**Desktop (please complete the following information):**
OS: Windows 10
Unity Version 2022.1.7

**Comment by CaydenJessen** [comment]
Issue fixed by changing the groundcheck from collision detection to ray-casting
