### ISSUE TITLE
Movement of Player after they die

### ISSUE THREAD

**Issue by AndyLee-SH** [CaydenJessen/Stay-Hidden_GAME#5]
Describe the bug
When Player dies, the player can still be moved around on screen

To Reproduce

Player run up to NPC
NPC contact Player
Player's health goes down to zero
Game over screen comes up
Player can still be moved left and right

Desktop (please complete the following information):
OS: Windows 10
Unity Version 2022.1.7

**Comment by CaydenJessen** [comment]
To fix this I created a bool for if the player was alive. The player and camera can only move when this value is true. When the player dies it is set to false.
