### ISSUE TITLE
Player can sprint while hiding skill is activated 

### ISSUE THREAD

**Issue by AndyLee-SH** [CaydenJessen/Stay-Hidden_GAME#7]
Describe the bug
Player are able to run when they are hiding.

To Reproduce

Player use the hide skill.
Player press shift to run 
Player are able to move really fast while hiding.

Desktop (please complete the following information):

OS: Windows 10
Unity Version 2022.1.7

**Comment by CaydenJessen** [comment]
To fix this I set the boolean isRunning false when the player presses "cntrl" and uses the hide ability. Because of this the player won't be able to run when hiding is enabled.
