### ISSUE TITLE
Hiding in shadow bug

### ISSUE THREAD

**Issue by AndyLee-SH** [CaydenJessen/Stay-Hidden_GAME#8]
Describe the bug
When player enter the shadow and use the hiding skill and unhides, player won't heal straight away, healing factor takes a second or two to kick in.

To Reproduce

Player enters the shadow area
Player use hide skills
Player unhides
Player's health doesn't regenerate straight away.

Desktop (please complete the following information):

OS: Windows 10
Unity Version 2022.1.7

**Comment by ILikeDogss** [comment]
Issue has been solved by making another bool statement, all works as intended now
